-- This file has been generated by Ion. Do not edit.
return {
    [1] = "lua:ioncore.restart()",
    [2] = "framename:slithe",
    [3] = "workspacelayout:",
    [4] = "workspacename:snarf-hbrsrv",
    [5] = "framename:big",
    [6] = "workspacename:snarf",
    [7] = "workspacename:random",
    [8] = "workspacename:misc",
    [9] = "workspacename:liono",
    [10] = "workspacename:ESX",
    [11] = "workspacename:view",
    [12] = "workspacename:edit_",
    [13] = "workspacename:edit",
    [14] = "framename:edit",
}

