-- This file has been generated by Ion. Do not edit.
return {
    [1] = "framename:esxvm3",
    [2] = "framename:esxvm2",
    [3] = "workspacelayout:",
    [4] = "workspacename:esxvm4",
    [5] = "framename:misc",
    [6] = "workspacename:esxvm3",
    [7] = "workspacename:esxvm1",
    [8] = "workspacename:esxvm",
    [9] = "workspacename:edit2",
    [10] = "framename:edit1",
}

