#!/bin/bash

#read -sp "Keymap bug - first touch a key in each server, then press enter"
IP=10.0.2.2

# workaround for keymap bug
# DISPLAY=10.17.119.64:0 xmodmap -pk &
# DISPLAY=10.17.119.64:1 xterm &

notion -display $IP:1 -session session-host-1 >/tmp/ionlog1 2>&1 &
notion -display $IP:2 -session session-host-2 >/tmp/ionlog2 2>&1 &

# DISPLAY=$IP:0 urxvt &
