-- This file has been generated by Ion. Do not edit.
return {
    [0] = {
        ["type"] = "WRootWin",
        ["name"] = "WRootWin",
        ["managed"] = {
            [1] = {
                ["type"] = "WGroupWS",
                ["name"] = "dbc1",
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1200,
                    ["h"] = 1570,
                },
                ["switchto"] = true,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<1>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1200,
                            ["h"] = 1570,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1555,
                            ["tl"] = {
                                ["tls"] = 780,
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<1>",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW",
                                                ["geom"] = {
                                                    ["y"] = 19,
                                                    ["x"] = 1,
                                                    ["w"] = 1198,
                                                    ["h"] = 760,
                                                },
                                                ["switchto"] = true,
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["bottom"] = true,
                                                        ["windowid"] = 8388615,
                                                        ["checkcode"] = 15,
                                                        ["sizepolicy"] = "full",
                                                        ["geom"] = {
                                                            ["y"] = 1,
                                                            ["x"] = 2,
                                                            ["w"] = 1194,
                                                            ["h"] = 758,
                                                        },
                                                        ["level"] = 1,
                                                    },
                                                },
                                                ["level"] = 0,
                                            },
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["dir"] = "vertical",
                                ["brs"] = 775,
                                ["br"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<3>",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW<2>",
                                                ["geom"] = {
                                                    ["y"] = 19,
                                                    ["x"] = 1,
                                                    ["w"] = 1198,
                                                    ["h"] = 755,
                                                },
                                                ["switchto"] = true,
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["bottom"] = true,
                                                        ["windowid"] = 12582919,
                                                        ["checkcode"] = 16,
                                                        ["sizepolicy"] = "full",
                                                        ["geom"] = {
                                                            ["y"] = 5,
                                                            ["x"] = 2,
                                                            ["w"] = 1194,
                                                            ["h"] = 745,
                                                        },
                                                        ["level"] = 1,
                                                    },
                                                },
                                                ["level"] = 0,
                                            },
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [2] = {
                ["type"] = "WGroupWS",
                ["name"] = "dbc2",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1200,
                    ["h"] = 1570,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1200,
                            ["h"] = 1570,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1555,
                            ["tl"] = {
                                ["tls"] = 762,
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW<8>",
                                                ["geom"] = {
                                                    ["y"] = 19,
                                                    ["x"] = 1,
                                                    ["w"] = 1198,
                                                    ["h"] = 742,
                                                },
                                                ["switchto"] = true,
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["bottom"] = true,
                                                        ["windowid"] = 25165831,
                                                        ["checkcode"] = 17,
                                                        ["sizepolicy"] = "full",
                                                        ["geom"] = {
                                                            ["y"] = 5,
                                                            ["x"] = 2,
                                                            ["w"] = 1194,
                                                            ["h"] = 732,
                                                        },
                                                        ["level"] = 1,
                                                    },
                                                },
                                                ["level"] = 0,
                                            },
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["dir"] = "vertical",
                                ["brs"] = 793,
                                ["br"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<4>",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW<4>",
                                                ["geom"] = {
                                                    ["y"] = 19,
                                                    ["x"] = 1,
                                                    ["w"] = 1198,
                                                    ["h"] = 773,
                                                },
                                                ["switchto"] = true,
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["bottom"] = true,
                                                        ["windowid"] = 16777223,
                                                        ["checkcode"] = 18,
                                                        ["sizepolicy"] = "full",
                                                        ["geom"] = {
                                                            ["y"] = 1,
                                                            ["x"] = 2,
                                                            ["w"] = 1194,
                                                            ["h"] = 771,
                                                        },
                                                        ["level"] = 1,
                                                    },
                                                },
                                                ["level"] = 0,
                                            },
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [3] = {
                ["type"] = "WGroupWS",
                ["name"] = "dbc3",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1200,
                    ["h"] = 1570,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<2>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1200,
                            ["h"] = 1570,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1555,
                            ["tl"] = {
                                ["tls"] = 715,
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<2>",
                                        ["managed"] = {
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["dir"] = "vertical",
                                ["brs"] = 840,
                                ["br"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<5>",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW<7>",
                                                ["geom"] = {
                                                    ["y"] = 19,
                                                    ["x"] = 1,
                                                    ["w"] = 1198,
                                                    ["h"] = 820,
                                                },
                                                ["switchto"] = true,
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["bottom"] = true,
                                                        ["windowid"] = 23068679,
                                                        ["checkcode"] = 19,
                                                        ["sizepolicy"] = "full",
                                                        ["geom"] = {
                                                            ["y"] = 5,
                                                            ["x"] = 2,
                                                            ["w"] = 1194,
                                                            ["h"] = 810,
                                                        },
                                                        ["level"] = 1,
                                                    },
                                                },
                                                ["level"] = 0,
                                            },
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [4] = {
                ["type"] = "WGroupWS",
                ["name"] = "xports",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1200,
                    ["h"] = 1570,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<3>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1200,
                            ["h"] = 1570,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1555,
                            ["tl"] = {
                                ["tls"] = 778,
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<6>",
                                        ["managed"] = {
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["dir"] = "vertical",
                                ["brs"] = 777,
                                ["br"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<7>",
                                        ["managed"] = {
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [5] = {
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["y"] = 331,
                            ["x"] = 477,
                            ["w"] = 640,
                            ["h"] = 480,
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*",
                        ["bottom"] = true,
                        ["level"] = 1025,
                        ["mode"] = 0,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                    },
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*",
                ["pseudomodal"] = true,
                ["level"] = 1,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1200,
                    ["h"] = 1570,
                },
                ["hidden"] = true,
            },
        },
    },
}

