-- This file has been generated by Ion. Do not edit.
return {
    [1] = "framename:misc",
    [2] = "framename:debugging",
    [3] = "framename:logs",
    [4] = "workspacelayout:",
    [5] = "workspacename:local",
    [6] = "workspacename:big",
    [7] = "workspacename:random",
    [8] = "workspacename:debugging",
    [9] = "workspacename:testing",
    [10] = "workspacename:hbrsrv",
    [11] = "workspacename:perforce",
    [12] = "framename:compile",
}

