-- This file has been generated by Ion. Do not edit.
return {
    [1] = "workspacelayout:",
    [2] = "workspacename:pa-dbc2",
    [3] = "workspacename:pa-dbc",
    [4] = "workspacename:tree2",
    [5] = "framename:tree1",
}

