-- This file has been generated by Ion. Do not edit.
return {
    [0] = {
        ["type"] = "WRootWin",
        ["name"] = "WRootWin",
        ["managed"] = {
            [1] = {
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS",
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1850,
                    ["h"] = 1080,
                },
                ["switchto"] = true,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1850,
                            ["h"] = 1080,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1065,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame",
                                    ["managed"] = {
                                        [1] = {
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW",
                                            ["geom"] = {
                                                ["y"] = 21,
                                                ["x"] = 1,
                                                ["w"] = 1848,
                                                ["h"] = 1043,
                                            },
                                            ["switchto"] = true,
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["windowid"] = 4194311,
                                                    ["checkcode"] = 1,
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["y"] = 6,
                                                        ["x"] = 2,
                                                        ["w"] = 1845,
                                                        ["h"] = 1031,
                                                    },
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["level"] = 0,
                                        },
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [2] = {
                ["type"] = "WGroupWS",
                ["name"] = "meh",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1850,
                    ["h"] = 1080,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<1>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1850,
                            ["h"] = 1080,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1065,
                            ["tl"] = {
                                ["tls"] = 533,
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<1>",
                                        ["managed"] = {
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["dir"] = "vertical",
                                ["brs"] = 532,
                                ["br"] = {
                                    ["tls"] = 925,
                                    ["tl"] = {
                                        ["regparams"] = {
                                            ["mode"] = 1,
                                            ["type"] = "WFrame",
                                            ["name"] = "WFrame<2>",
                                            ["managed"] = {
                                            },
                                        },
                                        ["type"] = "WSplitRegion",
                                    },
                                    ["dir"] = "horizontal",
                                    ["brs"] = 925,
                                    ["br"] = {
                                        ["regparams"] = {
                                            ["mode"] = 1,
                                            ["type"] = "WFrame",
                                            ["name"] = "WFrame<3>",
                                            ["managed"] = {
                                            },
                                        },
                                        ["type"] = "WSplitRegion",
                                    },
                                    ["type"] = "WSplitSplit",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [3] = {
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["y"] = 300,
                            ["x"] = 605,
                            ["w"] = 640,
                            ["h"] = 480,
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*",
                        ["bottom"] = true,
                        ["level"] = 1025,
                        ["mode"] = 0,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                    },
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*",
                ["pseudomodal"] = true,
                ["level"] = 1,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1850,
                    ["h"] = 1080,
                },
                ["hidden"] = true,
            },
        },
    },
}

