-- This file has been generated by Ion. Do not edit.
return {
    [1] = "workspacelayout:",
    [2] = "workspacename:big",
    [3] = "workspacename:random",
    [4] = "workspacename:debugging",
    [5] = "workspacename:testing",
    [6] = "workspacename:hbrsrv",
    [7] = "workspacename:perforce",
    [8] = "framename:compile",
}

