-- This file has been generated by notion. Do not edit.
return {
    [0] = {
        ["name"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["name"] = "WGroupWS",
                ["geom"] = {
                    ["x"] = 0,
                    ["w"] = 1096,
                    ["h"] = 1395,
                    ["y"] = 0,
                },
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["switchto"] = true,
                ["level"] = 0,
                ["managed"] = {
                    [1] = {
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                        ["geom"] = {
                            ["x"] = 0,
                            ["w"] = 1096,
                            ["h"] = 1395,
                            ["y"] = 0,
                        },
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["tls"] = 545,
                            ["type"] = "WSplitSplit",
                            ["tl"] = {
                                ["tls"] = 1380,
                                ["type"] = "WSplitSplit",
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["name"] = "WFrame",
                                        ["mode"] = 1,
                                        ["managed"] = {
                                            [1] = {
                                                ["name"] = "WGroupCW",
                                                ["geom"] = {
                                                    ["x"] = 1,
                                                    ["w"] = 543,
                                                    ["h"] = 1358,
                                                    ["y"] = 21,
                                                },
                                                ["type"] = "WGroupCW",
                                                ["sizepolicy"] = "full",
                                                ["switchto"] = true,
                                                ["level"] = 0,
                                                ["managed"] = {
                                                    [1] = {
                                                        ["windowid"] = 1572871,
                                                        ["checkcode"] = 1,
                                                        ["geom"] = {
                                                            ["x"] = 1,
                                                            ["w"] = 540,
                                                            ["h"] = 1348,
                                                            ["y"] = 5,
                                                        },
                                                        ["type"] = "WClientWin",
                                                        ["sizepolicy"] = "full",
                                                        ["bottom"] = true,
                                                        ["level"] = 1,
                                                    },
                                                },
                                            },
                                        },
                                        ["type"] = "WFrame",
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["br"] = {
                                    ["type"] = "WSplitST",
                                },
                                ["brs"] = 15,
                                ["dir"] = "vertical",
                            },
                            ["br"] = {
                                ["regparams"] = {
                                    ["name"] = "WFrame<1>",
                                    ["mode"] = 1,
                                    ["managed"] = {
                                    },
                                    ["type"] = "WFrame",
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["brs"] = 551,
                            ["dir"] = "horizontal",
                        },
                        ["level"] = 0,
                    },
                },
            },
            [2] = {
                ["name"] = "*scratchws*",
                ["geom"] = {
                    ["x"] = 0,
                    ["w"] = 1096,
                    ["h"] = 1395,
                    ["y"] = 0,
                },
                ["type"] = "WGroupWS",
                ["level"] = 1,
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["sizepolicy"] = "full",
                ["pseudomodal"] = true,
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["name"] = "*scratchpad*",
                        ["mode"] = 0,
                        ["geom"] = {
                            ["x"] = 456,
                            ["w"] = 640,
                            ["h"] = 480,
                            ["y"] = 457,
                        },
                        ["type"] = "WFrame",
                        ["sizepolicy"] = "free_glue",
                        ["bottom"] = true,
                        ["level"] = 1025,
                        ["managed"] = {
                        },
                    },
                },
            },
        },
        ["type"] = "WScreen",
    },
}

