-- This file has been generated by Ion. Do not edit.
return {
    [1] = "workspacelayout:",
    [2] = "workspacename:pa-dbc2",
    [3] = "workspacename:pa-dbc",
    [4] = "workspacename:suite",
    [5] = "workspacename:delta",
    [6] = "framename:pxe-rsync",
    [7] = "workspacename:pxe-rscyn",
    [8] = "framename:UAT",
}

