-- This file has been generated by notion. Do not edit.
return {
    [1] = "framename:misc",
    [2] = "workspacelayout:",
    [3] = "workspacename:config",
    [4] = "workspacename:sql",
    [5] = "workspacename:3",
    [6] = "workspacename:go2",
    [7] = "framename:go",
}

