-- This file has been generated by notion. Do not edit.
return {
    [1] = "workspacelayout:",
    [2] = "workspacename:sql",
    [3] = "workspacename:3",
    [4] = "workspacename:go2",
    [5] = "framename:go",
}

