-- This file has been generated by notion. Do not edit.
return {
    [0] = {
        ["name"] = "WScreen",
        ["type"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["hidden"] = true,
                ["level"] = 0,
                ["managed"] = {
                    [1] = {
                        ["level"] = 0,
                        ["geom"] = {
                            ["w"] = 1098,
                            ["x"] = 0,
                            ["y"] = 0,
                            ["h"] = 1395,
                        },
                        ["bottom"] = true,
                        ["name"] = "WTiling",
                        ["split_tree"] = {
                            ["brs"] = 761,
                            ["dir"] = "vertical",
                            ["br"] = {
                                ["brs"] = 15,
                                ["dir"] = "vertical",
                                ["br"] = {
                                    ["type"] = "WSplitST",
                                },
                                ["tls"] = 746,
                                ["type"] = "WSplitSplit",
                                ["tl"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["name"] = "Tiling Frame<1>",
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["managed"] = {
                                            [1] = {
                                                ["level"] = 0,
                                                ["managed"] = {
                                                    [1] = {
                                                        ["level"] = 1,
                                                        ["bottom"] = true,
                                                        ["windowid"] = 4194311,
                                                        ["geom"] = {
                                                            ["w"] = 1092,
                                                            ["x"] = 2,
                                                            ["y"] = 0,
                                                            ["h"] = 724,
                                                        },
                                                        ["sizepolicy"] = "full",
                                                        ["type"] = "WClientWin",
                                                        ["checkcode"] = 4,
                                                    },
                                                },
                                                ["geom"] = {
                                                    ["w"] = 1096,
                                                    ["x"] = 1,
                                                    ["y"] = 21,
                                                    ["h"] = 724,
                                                },
                                                ["name"] = "WGroupCW<4>",
                                                ["switchto"] = true,
                                                ["type"] = "WGroupCW",
                                                ["sizepolicy"] = "full",
                                            },
                                        },
                                    },
                                },
                            },
                            ["tls"] = 634,
                            ["type"] = "WSplitSplit",
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["name"] = "Tiling Frame",
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["managed"] = {
                                        [1] = {
                                            ["level"] = 0,
                                            ["managed"] = {
                                                [1] = {
                                                    ["level"] = 1,
                                                    ["bottom"] = true,
                                                    ["windowid"] = 2621447,
                                                    ["geom"] = {
                                                        ["w"] = 1092,
                                                        ["x"] = 2,
                                                        ["y"] = 0,
                                                        ["h"] = 612,
                                                    },
                                                    ["sizepolicy"] = "full",
                                                    ["type"] = "WClientWin",
                                                    ["checkcode"] = 3,
                                                },
                                            },
                                            ["geom"] = {
                                                ["w"] = 1096,
                                                ["x"] = 1,
                                                ["y"] = 21,
                                                ["h"] = 612,
                                            },
                                            ["name"] = "WGroupCW<2>",
                                            ["switchto"] = true,
                                            ["type"] = "WGroupCW",
                                            ["sizepolicy"] = "full",
                                        },
                                    },
                                },
                            },
                        },
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                    },
                },
                ["geom"] = {
                    ["w"] = 1098,
                    ["x"] = 0,
                    ["y"] = 0,
                    ["h"] = 1395,
                },
                ["name"] = "go",
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
            },
            [2] = {
                ["hidden"] = true,
                ["level"] = 0,
                ["managed"] = {
                    [1] = {
                        ["level"] = 0,
                        ["geom"] = {
                            ["w"] = 1098,
                            ["x"] = 0,
                            ["y"] = 0,
                            ["h"] = 1395,
                        },
                        ["bottom"] = true,
                        ["name"] = "WTiling<1>",
                        ["split_tree"] = {
                            ["brs"] = 705,
                            ["dir"] = "vertical",
                            ["br"] = {
                                ["brs"] = 15,
                                ["dir"] = "vertical",
                                ["br"] = {
                                    ["type"] = "WSplitST",
                                },
                                ["tls"] = 690,
                                ["type"] = "WSplitSplit",
                                ["tl"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["name"] = "Tiling Frame<2>",
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["managed"] = {
                                            [1] = {
                                                ["level"] = 0,
                                                ["managed"] = {
                                                    [1] = {
                                                        ["level"] = 1,
                                                        ["bottom"] = true,
                                                        ["windowid"] = 5242887,
                                                        ["geom"] = {
                                                            ["w"] = 1092,
                                                            ["x"] = 2,
                                                            ["y"] = 4,
                                                            ["h"] = 660,
                                                        },
                                                        ["sizepolicy"] = "full",
                                                        ["type"] = "WClientWin",
                                                        ["checkcode"] = 6,
                                                    },
                                                },
                                                ["geom"] = {
                                                    ["w"] = 1096,
                                                    ["x"] = 1,
                                                    ["y"] = 21,
                                                    ["h"] = 668,
                                                },
                                                ["name"] = "WGroupCW<6>",
                                                ["switchto"] = true,
                                                ["type"] = "WGroupCW",
                                                ["sizepolicy"] = "full",
                                            },
                                        },
                                    },
                                },
                            },
                            ["tls"] = 690,
                            ["type"] = "WSplitSplit",
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["name"] = "WFrame<1>",
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["managed"] = {
                                        [1] = {
                                            ["level"] = 0,
                                            ["managed"] = {
                                                [1] = {
                                                    ["level"] = 1,
                                                    ["bottom"] = true,
                                                    ["windowid"] = 4718599,
                                                    ["geom"] = {
                                                        ["w"] = 1092,
                                                        ["x"] = 2,
                                                        ["y"] = 4,
                                                        ["h"] = 660,
                                                    },
                                                    ["sizepolicy"] = "full",
                                                    ["type"] = "WClientWin",
                                                    ["checkcode"] = 5,
                                                },
                                            },
                                            ["geom"] = {
                                                ["w"] = 1096,
                                                ["x"] = 1,
                                                ["y"] = 21,
                                                ["h"] = 668,
                                            },
                                            ["name"] = "WGroupCW<5>",
                                            ["switchto"] = true,
                                            ["type"] = "WGroupCW",
                                            ["sizepolicy"] = "full",
                                        },
                                    },
                                },
                            },
                        },
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                    },
                },
                ["geom"] = {
                    ["w"] = 1098,
                    ["x"] = 0,
                    ["y"] = 0,
                    ["h"] = 1395,
                },
                ["name"] = "go2",
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
            },
            [3] = {
                ["hidden"] = true,
                ["level"] = 0,
                ["managed"] = {
                    [1] = {
                        ["level"] = 0,
                        ["geom"] = {
                            ["w"] = 1098,
                            ["x"] = 0,
                            ["y"] = 0,
                            ["h"] = 1395,
                        },
                        ["bottom"] = true,
                        ["name"] = "WTiling<2>",
                        ["split_tree"] = {
                            ["brs"] = 15,
                            ["dir"] = "vertical",
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["tls"] = 1380,
                            ["type"] = "WSplitSplit",
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["name"] = "WFrame",
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["managed"] = {
                                    },
                                },
                            },
                        },
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                    },
                },
                ["geom"] = {
                    ["w"] = 1098,
                    ["x"] = 0,
                    ["y"] = 0,
                    ["h"] = 1395,
                },
                ["name"] = "3",
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
            },
            [4] = {
                ["hidden"] = true,
                ["level"] = 0,
                ["managed"] = {
                    [1] = {
                        ["level"] = 0,
                        ["geom"] = {
                            ["w"] = 1098,
                            ["x"] = 0,
                            ["y"] = 0,
                            ["h"] = 1395,
                        },
                        ["bottom"] = true,
                        ["name"] = "WTiling<3>",
                        ["split_tree"] = {
                            ["brs"] = 15,
                            ["dir"] = "vertical",
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["tls"] = 1380,
                            ["type"] = "WSplitSplit",
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["saved_w"] = 1098,
                                    ["managed"] = {
                                        [1] = {
                                            ["level"] = 0,
                                            ["managed"] = {
                                                [1] = {
                                                    ["level"] = 1,
                                                    ["bottom"] = true,
                                                    ["windowid"] = 1572871,
                                                    ["geom"] = {
                                                        ["w"] = 1092,
                                                        ["x"] = 2,
                                                        ["y"] = 5,
                                                        ["h"] = 1348,
                                                    },
                                                    ["sizepolicy"] = "full",
                                                    ["type"] = "WClientWin",
                                                    ["checkcode"] = 7,
                                                },
                                            },
                                            ["hidden"] = true,
                                            ["name"] = "WGroupCW",
                                            ["geom"] = {
                                                ["w"] = 1096,
                                                ["x"] = 1,
                                                ["y"] = 21,
                                                ["h"] = 1358,
                                            },
                                            ["type"] = "WGroupCW",
                                            ["sizepolicy"] = "full",
                                        },
                                        [2] = {
                                            ["level"] = 0,
                                            ["managed"] = {
                                                [1] = {
                                                    ["level"] = 1,
                                                    ["bottom"] = true,
                                                    ["windowid"] = 2097159,
                                                    ["geom"] = {
                                                        ["w"] = 1092,
                                                        ["x"] = 2,
                                                        ["y"] = 5,
                                                        ["h"] = 1348,
                                                    },
                                                    ["sizepolicy"] = "full",
                                                    ["type"] = "WClientWin",
                                                    ["checkcode"] = 8,
                                                },
                                            },
                                            ["geom"] = {
                                                ["w"] = 1096,
                                                ["x"] = 1,
                                                ["y"] = 21,
                                                ["h"] = 1358,
                                            },
                                            ["name"] = "WGroupCW<1>",
                                            ["switchto"] = true,
                                            ["type"] = "WGroupCW",
                                            ["sizepolicy"] = "full",
                                        },
                                    },
                                    ["saved_x"] = 0,
                                    ["name"] = "WFrame<3>",
                                    ["type"] = "WFrame",
                                    ["mode"] = 1,
                                },
                            },
                        },
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                    },
                },
                ["geom"] = {
                    ["w"] = 1098,
                    ["x"] = 0,
                    ["y"] = 0,
                    ["h"] = 1395,
                },
                ["name"] = "sql",
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
            },
            [5] = {
                ["geom"] = {
                    ["w"] = 1098,
                    ["x"] = 0,
                    ["y"] = 0,
                    ["h"] = 1395,
                },
                ["level"] = 0,
                ["managed"] = {
                    [1] = {
                        ["level"] = 0,
                        ["geom"] = {
                            ["w"] = 1098,
                            ["x"] = 0,
                            ["y"] = 0,
                            ["h"] = 1395,
                        },
                        ["bottom"] = true,
                        ["name"] = "WTiling<4>",
                        ["split_tree"] = {
                            ["brs"] = 15,
                            ["dir"] = "vertical",
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["tls"] = 1380,
                            ["type"] = "WSplitSplit",
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["name"] = "WFrame<4>",
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["managed"] = {
                                        [1] = {
                                            ["level"] = 0,
                                            ["managed"] = {
                                                [1] = {
                                                    ["level"] = 1,
                                                    ["bottom"] = true,
                                                    ["windowid"] = 3670023,
                                                    ["geom"] = {
                                                        ["w"] = 1092,
                                                        ["x"] = 2,
                                                        ["y"] = 5,
                                                        ["h"] = 1348,
                                                    },
                                                    ["sizepolicy"] = "full",
                                                    ["type"] = "WClientWin",
                                                    ["checkcode"] = 9,
                                                },
                                            },
                                            ["geom"] = {
                                                ["w"] = 1096,
                                                ["x"] = 1,
                                                ["y"] = 21,
                                                ["h"] = 1358,
                                            },
                                            ["name"] = "WGroupCW<3>",
                                            ["switchto"] = true,
                                            ["type"] = "WGroupCW",
                                            ["sizepolicy"] = "full",
                                        },
                                    },
                                },
                            },
                        },
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "config",
                ["switchto"] = true,
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
            },
            [6] = {
                ["unnumbered"] = true,
                ["name"] = "*scratchws*",
                ["geom"] = {
                    ["w"] = 1098,
                    ["x"] = 0,
                    ["y"] = 0,
                    ["h"] = 1395,
                },
                ["level"] = 1,
                ["initial_outputs"] = {
                },
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["w"] = 640,
                            ["x"] = 458,
                            ["y"] = 915,
                            ["h"] = 480,
                        },
                        ["level"] = 1025,
                        ["managed"] = {
                        },
                        ["bottom"] = true,
                        ["name"] = "*scratchpad*",
                        ["sizepolicy"] = "free_glue_southeast",
                        ["type"] = "WFrame",
                        ["mode"] = 0,
                    },
                },
                ["hidden"] = true,
                ["pseudomodal"] = true,
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
            },
        },
    },
}

