-- This file has been generated by Ion. Do not edit.
return {
    [1] = "workspacelayout:",
    [2] = "workspacename:misc",
    [3] = "workspacename:liono",
    [4] = "workspacename:ESX",
    [5] = "workspacename:view",
    [6] = "workspacename:edit_",
    [7] = "workspacename:edit",
    [8] = "framename:edit",
}

