-- This file has been generated by Ion. Do not edit.
return {
    [0] = {
        ["type"] = "WRootWin",
        ["name"] = "WRootWin",
        ["managed"] = {
            [1] = {
                ["type"] = "WGroupWS",
                ["name"] = "edit",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1594,
                    ["h"] = 1138,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1594,
                            ["h"] = 1138,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1123,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [2] = {
                ["type"] = "WGroupWS",
                ["name"] = "edit_",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1594,
                    ["h"] = 1138,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<1>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1594,
                            ["h"] = 1138,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1123,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<1>",
                                    ["managed"] = {
                                        [1] = {
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW<4>",
                                            ["geom"] = {
                                                ["y"] = 21,
                                                ["x"] = 1,
                                                ["w"] = 1592,
                                                ["h"] = 1101,
                                            },
                                            ["switchto"] = true,
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["windowid"] = 14680074,
                                                    ["checkcode"] = 1,
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["y"] = 2,
                                                        ["x"] = 3,
                                                        ["w"] = 1586,
                                                        ["h"] = 1096,
                                                    },
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["level"] = 0,
                                        },
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [3] = {
                ["type"] = "WGroupWS",
                ["name"] = "view",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1594,
                    ["h"] = 1138,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<2>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1594,
                            ["h"] = 1138,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1123,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<2>",
                                    ["managed"] = {
                                        [1] = {
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW<5>",
                                            ["geom"] = {
                                                ["y"] = 21,
                                                ["x"] = 1,
                                                ["w"] = 1592,
                                                ["h"] = 1101,
                                            },
                                            ["switchto"] = true,
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["windowid"] = 16777226,
                                                    ["checkcode"] = 2,
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["y"] = 2,
                                                        ["x"] = 3,
                                                        ["w"] = 1586,
                                                        ["h"] = 1096,
                                                    },
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["level"] = 0,
                                        },
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [4] = {
                ["type"] = "WGroupWS",
                ["name"] = "ESX",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1594,
                    ["h"] = 1138,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<3>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1594,
                            ["h"] = 1138,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1123,
                            ["tl"] = {
                                ["tls"] = 564,
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<3>",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW<7>",
                                                ["hidden"] = true,
                                                ["geom"] = {
                                                    ["y"] = 21,
                                                    ["x"] = 1,
                                                    ["w"] = 1592,
                                                    ["h"] = 542,
                                                },
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["bottom"] = true,
                                                        ["windowid"] = 25165834,
                                                        ["checkcode"] = 3,
                                                        ["sizepolicy"] = "full",
                                                        ["geom"] = {
                                                            ["y"] = 3,
                                                            ["x"] = 3,
                                                            ["w"] = 1586,
                                                            ["h"] = 537,
                                                        },
                                                        ["level"] = 1,
                                                    },
                                                },
                                                ["level"] = 0,
                                            },
                                            [2] = {
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW<3>",
                                                ["geom"] = {
                                                    ["y"] = 21,
                                                    ["x"] = 1,
                                                    ["w"] = 1592,
                                                    ["h"] = 542,
                                                },
                                                ["switchto"] = true,
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["bottom"] = true,
                                                        ["windowid"] = 12582922,
                                                        ["checkcode"] = 4,
                                                        ["sizepolicy"] = "full",
                                                        ["geom"] = {
                                                            ["y"] = 3,
                                                            ["x"] = 3,
                                                            ["w"] = 1586,
                                                            ["h"] = 537,
                                                        },
                                                        ["level"] = 1,
                                                    },
                                                },
                                                ["level"] = 0,
                                            },
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["dir"] = "vertical",
                                ["brs"] = 559,
                                ["br"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<6>",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW<2>",
                                                ["geom"] = {
                                                    ["y"] = 21,
                                                    ["x"] = 1,
                                                    ["w"] = 1592,
                                                    ["h"] = 537,
                                                },
                                                ["switchto"] = true,
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["bottom"] = true,
                                                        ["windowid"] = 10485770,
                                                        ["checkcode"] = 5,
                                                        ["sizepolicy"] = "full",
                                                        ["geom"] = {
                                                            ["y"] = 0,
                                                            ["x"] = 3,
                                                            ["w"] = 1586,
                                                            ["h"] = 537,
                                                        },
                                                        ["level"] = 1,
                                                    },
                                                },
                                                ["level"] = 0,
                                            },
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [5] = {
                ["type"] = "WGroupWS",
                ["name"] = "liono",
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1594,
                    ["h"] = 1138,
                },
                ["switchto"] = true,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<4>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1594,
                            ["h"] = 1138,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1123,
                            ["tl"] = {
                                ["tls"] = 562,
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<4>",
                                        ["managed"] = {
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["dir"] = "vertical",
                                ["brs"] = 561,
                                ["br"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<7>",
                                        ["managed"] = {
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [6] = {
                ["type"] = "WGroupWS",
                ["name"] = "snarf",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1594,
                    ["h"] = 1138,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<7>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1594,
                            ["h"] = 1138,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1123,
                            ["tl"] = {
                                ["tls"] = 562,
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<10>",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW<9>",
                                                ["geom"] = {
                                                    ["y"] = 21,
                                                    ["x"] = 1,
                                                    ["w"] = 1592,
                                                    ["h"] = 540,
                                                },
                                                ["switchto"] = true,
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["bottom"] = true,
                                                        ["windowid"] = 27262986,
                                                        ["checkcode"] = 6,
                                                        ["sizepolicy"] = "full",
                                                        ["geom"] = {
                                                            ["y"] = 2,
                                                            ["x"] = 3,
                                                            ["w"] = 1586,
                                                            ["h"] = 537,
                                                        },
                                                        ["level"] = 1,
                                                    },
                                                },
                                                ["level"] = 0,
                                            },
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["dir"] = "vertical",
                                ["brs"] = 561,
                                ["br"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<11>",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW<8>",
                                                ["geom"] = {
                                                    ["y"] = 21,
                                                    ["x"] = 1,
                                                    ["w"] = 1592,
                                                    ["h"] = 539,
                                                },
                                                ["switchto"] = true,
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["bottom"] = true,
                                                        ["windowid"] = 31457290,
                                                        ["checkcode"] = 7,
                                                        ["sizepolicy"] = "full",
                                                        ["geom"] = {
                                                            ["y"] = 1,
                                                            ["x"] = 3,
                                                            ["w"] = 1586,
                                                            ["h"] = 537,
                                                        },
                                                        ["level"] = 1,
                                                    },
                                                },
                                                ["level"] = 0,
                                            },
                                            [2] = {
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW<11>",
                                                ["hidden"] = true,
                                                ["geom"] = {
                                                    ["y"] = 21,
                                                    ["x"] = 1,
                                                    ["w"] = 1592,
                                                    ["h"] = 539,
                                                },
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["bottom"] = true,
                                                        ["windowid"] = 29360138,
                                                        ["checkcode"] = 8,
                                                        ["sizepolicy"] = "full",
                                                        ["geom"] = {
                                                            ["y"] = 1,
                                                            ["x"] = 3,
                                                            ["w"] = 1586,
                                                            ["h"] = 537,
                                                        },
                                                        ["level"] = 1,
                                                    },
                                                },
                                                ["level"] = 0,
                                            },
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [7] = {
                ["type"] = "WGroupWS",
                ["name"] = "snarf-hbrsrv",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1594,
                    ["h"] = 1138,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<8>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1594,
                            ["h"] = 1138,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1123,
                            ["tl"] = {
                                ["tls"] = 554,
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<5>",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW<10>",
                                                ["geom"] = {
                                                    ["y"] = 21,
                                                    ["x"] = 1,
                                                    ["w"] = 1592,
                                                    ["h"] = 532,
                                                },
                                                ["switchto"] = true,
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["bottom"] = true,
                                                        ["windowid"] = 37748746,
                                                        ["checkcode"] = 9,
                                                        ["sizepolicy"] = "full",
                                                        ["geom"] = {
                                                            ["y"] = 4,
                                                            ["x"] = 3,
                                                            ["w"] = 1586,
                                                            ["h"] = 524,
                                                        },
                                                        ["level"] = 1,
                                                    },
                                                },
                                                ["level"] = 0,
                                            },
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["dir"] = "vertical",
                                ["brs"] = 569,
                                ["br"] = {
                                    ["tls"] = 792,
                                    ["tl"] = {
                                        ["regparams"] = {
                                            ["mode"] = 1,
                                            ["type"] = "WFrame",
                                            ["name"] = "WFrame<12>",
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WGroupCW",
                                                    ["name"] = "WGroupCW<12>",
                                                    ["geom"] = {
                                                        ["y"] = 21,
                                                        ["x"] = 1,
                                                        ["w"] = 790,
                                                        ["h"] = 547,
                                                    },
                                                    ["switchto"] = true,
                                                    ["sizepolicy"] = "full",
                                                    ["managed"] = {
                                                        [1] = {
                                                            ["type"] = "WClientWin",
                                                            ["bottom"] = true,
                                                            ["windowid"] = 39845898,
                                                            ["checkcode"] = 10,
                                                            ["sizepolicy"] = "full",
                                                            ["geom"] = {
                                                                ["y"] = 5,
                                                                ["x"] = 1,
                                                                ["w"] = 788,
                                                                ["h"] = 537,
                                                            },
                                                            ["level"] = 1,
                                                        },
                                                    },
                                                    ["level"] = 0,
                                                },
                                            },
                                        },
                                        ["type"] = "WSplitRegion",
                                    },
                                    ["dir"] = "horizontal",
                                    ["brs"] = 802,
                                    ["br"] = {
                                        ["regparams"] = {
                                            ["mode"] = 1,
                                            ["type"] = "WFrame",
                                            ["name"] = "WFrame<13>",
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WGroupCW",
                                                    ["name"] = "WGroupCW<13>",
                                                    ["geom"] = {
                                                        ["y"] = 21,
                                                        ["x"] = 1,
                                                        ["w"] = 800,
                                                        ["h"] = 547,
                                                    },
                                                    ["switchto"] = true,
                                                    ["sizepolicy"] = "full",
                                                    ["managed"] = {
                                                        [1] = {
                                                            ["type"] = "WClientWin",
                                                            ["bottom"] = true,
                                                            ["windowid"] = 41943050,
                                                            ["checkcode"] = 11,
                                                            ["sizepolicy"] = "full",
                                                            ["geom"] = {
                                                                ["y"] = 5,
                                                                ["x"] = 3,
                                                                ["w"] = 795,
                                                                ["h"] = 537,
                                                            },
                                                            ["level"] = 1,
                                                        },
                                                    },
                                                    ["level"] = 0,
                                                },
                                            },
                                        },
                                        ["type"] = "WSplitRegion",
                                    },
                                    ["type"] = "WSplitSplit",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [8] = {
                ["type"] = "WGroupWS",
                ["name"] = "misc",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1594,
                    ["h"] = 1138,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<5>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1594,
                            ["h"] = 1138,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1123,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<8>",
                                    ["managed"] = {
                                        [1] = {
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW<6>",
                                            ["geom"] = {
                                                ["y"] = 21,
                                                ["x"] = 1,
                                                ["w"] = 1592,
                                                ["h"] = 1101,
                                            },
                                            ["switchto"] = true,
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["windowid"] = 18874378,
                                                    ["checkcode"] = 12,
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["y"] = 2,
                                                        ["x"] = 3,
                                                        ["w"] = 1586,
                                                        ["h"] = 1096,
                                                    },
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["level"] = 0,
                                        },
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [9] = {
                ["type"] = "WGroupWS",
                ["name"] = "big",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1594,
                    ["h"] = 1138,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<6>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1594,
                            ["h"] = 1138,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1123,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<9>",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [10] = {
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["y"] = 329,
                            ["x"] = 477,
                            ["w"] = 640,
                            ["h"] = 480,
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*",
                        ["bottom"] = true,
                        ["level"] = 1025,
                        ["mode"] = 0,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                    },
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*",
                ["pseudomodal"] = true,
                ["level"] = 1,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1594,
                    ["h"] = 1138,
                },
                ["hidden"] = true,
            },
        },
    },
}

